# Generated by Django 4.2.4 on 2023-08-10 09:21

import ckeditor.fields
import colorfield.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Album",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("publish_date", models.DateTimeField(auto_now_add=True)),
                ("artist", models.CharField(max_length=200)),
                ("artist_slug", models.SlugField(unique=True)),
                ("title", models.CharField(max_length=200)),
                ("title_slug", models.SlugField(unique=True)),
                ("release_date", models.DateField()),
                ("tracklist", ckeditor.fields.RichTextField()),
                ("image", models.ImageField(upload_to="uploads/album_covers/")),
                ("review", ckeditor.fields.RichTextField()),
                ("highlights", ckeditor.fields.RichTextField()),
                ("lowlights", ckeditor.fields.RichTextField()),
                (
                    "rating",
                    models.PositiveIntegerField(
                        choices=[
                            (1, "1"),
                            (2, "2"),
                            (3, "3"),
                            (4, "4"),
                            (5, "5"),
                            (6, "6"),
                        ]
                    ),
                ),
                ("spotify_url", models.URLField(blank=True, null=True)),
                ("website_url", models.URLField(blank=True, null=True)),
                ("buy_url", models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="TagGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "color",
                    colorfield.fields.ColorField(
                        default="#FFFFFFFF",
                        image_field=None,
                        max_length=9,
                        samples=None,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TextBlock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("about_title", models.CharField(max_length=200)),
                ("about_content", ckeditor.fields.RichTextField()),
                ("playlist_title", models.CharField(max_length=200)),
                ("playlist_content", ckeditor.fields.RichTextField()),
                ("contact_title", models.CharField(max_length=200)),
                ("contact_content", ckeditor.fields.RichTextField()),
            ],
        ),
        migrations.CreateModel(
            name="UserScore",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "score",
                    models.PositiveIntegerField(
                        choices=[
                            (1, "1"),
                            (2, "2"),
                            (3, "3"),
                            (4, "4"),
                            (5, "5"),
                            (6, "6"),
                        ]
                    ),
                ),
                (
                    "album",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="HairMetalClub.album",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "tag_group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="HairMetalClub.taggroup",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="album",
            name="tags",
            field=models.ManyToManyField(blank=True, to="HairMetalClub.tag"),
        ),
    ]
