# Generated by Django 4.2.4 on 2023-08-10 09:29

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("HairMetalClub", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="album",
            name="highlights",
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="album",
            name="lowlights",
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
