# Generated by Django 4.2.4 on 2023-08-12 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("HairMetalClub", "0002_alter_album_highlights_alter_album_lowlights"),
    ]

    operations = [
        migrations.AlterField(
            model_name="album",
            name="tracklist",
            field=models.TextField(),
        ),
    ]
