# Generated by Django 4.2.4 on 2023-08-12 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("HairMetalClub", "0003_alter_album_tracklist"),
    ]

    operations = [
        migrations.AlterField(
            model_name="album",
            name="highlights",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="album",
            name="lowlights",
            field=models.TextField(),
        ),
    ]
