# Generated by Django 4.2.4 on 2023-08-12 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("HairMetalClub", "0004_alter_album_highlights_alter_album_lowlights"),
    ]

    operations = [
        migrations.AlterField(
            model_name="album",
            name="rating",
            field=models.PositiveIntegerField(
                choices=[
                    (1, "★☆☆☆☆☆"),
                    (2, "★★☆☆☆☆"),
                    (3, "★★★☆☆☆"),
                    (4, "★★★★☆☆"),
                    (5, "★★★★★☆"),
                    (6, "★★★★★★"),
                ],
                default=1,
            ),
        ),
    ]
