# Generated by Django 4.2.4 on 2023-08-23 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("HairMetalClub", "0006_alter_album_rating"),
    ]

    operations = [
        migrations.AlterField(
            model_name="album",
            name="highlights",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="album",
            name="lowlights",
            field=models.TextField(blank=True, null=True),
        ),
    ]
